# Generated by Django 3.1 on 2020-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='slug',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
